name: Solar System CI

on:
  push:
  workflow_dispatch:

jobs:
  install-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repositories
        uses: actions/checkout@v4

      - name: List repo files
        run: ls -ltr

      - uses: actions/setup-node@v4
        with:
          node-version: 22  

      - name: Install dependencies
        run: |
          cd solar-system
          npm install --no-audit
      - name: Unit Testing
        run: |
          cd solar-system
          npm test